# Copyright 2024 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Module extension for configuring orchestrion in rules_go."""

def _orchestrion_build_impl(ctx):
    """Build orchestrion from source."""
    version = ctx.attr.version
    
    # Download orchestrion source
    ctx.download_and_extract(
        url = "https://github.com/DataDog/orchestrion/archive/refs/tags/%s.zip" % version,
        stripPrefix = "orchestrion-%s" % version.lstrip("v"),
    )
    
    # Try to find go binary
    go_path = ctx.which("go")
    if not go_path:
        # Common locations for go binary
        for path in ["/usr/local/go/bin/go", "/opt/homebrew/bin/go", "/usr/bin/go"]:
            if ctx.path(path).exists:
                go_path = path
                break
    
    if not go_path:
        fail("Could not find 'go' binary. Please ensure Go is installed.")
    
    # Create build script
    ctx.file("build_orchestrion.sh", """#!/bin/bash
set -eu
export GO111MODULE=on
export GOPROXY=https://proxy.golang.org
export GOMODCACHE="$PWD/.gomodcache"
export GOCACHE="$PWD/.gocache"
mkdir -p "$GOMODCACHE" "$GOCACHE"
"{go}" build -trimpath -ldflags "-s -w" -o orchestrion .
""".format(go = go_path), executable = True)
    
    # Build orchestrion
    result = ctx.execute(
        ["./build_orchestrion.sh"],
        timeout = 600,
    )
    if result.return_code != 0:
        fail("Failed to build orchestrion: %s\n%s" % (result.stdout, result.stderr))
    
    # Create BUILD file
    ctx.file("BUILD.bazel", """# Generated by rules_go orchestrion extension
exports_files(["orchestrion"])

sh_binary(
    name = "orchestrion_bin",
    srcs = ["orchestrion.sh"],
    data = ["orchestrion"],
    visibility = ["//visibility:public"],
)

# Wrapper script that executes the orchestrion binary
genrule(
    name = "orchestrion_sh",
    outs = ["orchestrion.sh"],
    cmd = '''echo '#!/bin/bash
exec "$$(dirname "$$0")/orchestrion" "$$@"' > $@''',
)
""")

_orchestrion_build = repository_rule(
    implementation = _orchestrion_build_impl,
    attrs = {
        "version": attr.string(mandatory = True, doc = "Orchestrion version to build"),
    },
)

def _orchestrion_empty_impl(ctx):
    """Create an empty placeholder repo."""
    ctx.file("BUILD.bazel", """# Generated by rules_go orchestrion extension
# No orchestrion configured
filegroup(
    name = "orchestrion",
    srcs = [],
    visibility = ["//visibility:public"],
)
""")

_orchestrion_empty = repository_rule(
    implementation = _orchestrion_empty_impl,
)

def _orchestrion_ext_impl(module_ctx):
    # Look for orchestrion.from_source() calls from any module
    version = ""
    for mod in module_ctx.modules:
        for from_source in mod.tags.from_source:
            if from_source.version:
                version = from_source.version
                break
        if version:
            break
    
    if version:
        _orchestrion_build(
            name = "rules_go_orchestrion_tool",
            version = version,
        )
    else:
        _orchestrion_empty(
            name = "rules_go_orchestrion_tool",
        )

_from_source = tag_class(
    attrs = {
        "version": attr.string(
            mandatory = True,
            doc = "Orchestrion version to build (e.g., 'v1.5.0')",
        ),
    },
)

orchestrion_ext = module_extension(
    implementation = _orchestrion_ext_impl,
    tag_classes = {
        "from_source": _from_source,
    },
)

